spring:
  application:
    name: busDataManager
  data:
    mongodb:
      uri: mongodb://localhost:27017/busDataManager
      database: busDataManager
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
  metrics:
    export:
      prometheus:
        enabled: true