spring:
  application:
    name: busDataManager

  data:
    mongodb:
      uri: mongodb://localhost:27017/busDataManager
      database: busDataManager
  main:
    allow-bean-definition-overriding: true
