spring:
  application:
    name: busDataManager
  datasource:
    url: jdbc:h2:mem:testdb # Base de datos en memoria
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true # Habilitar la consola de H2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect